import React, { useEffect } from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const TermsConditions = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="home-container" style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh', backgroundColor: '#f8fafc' }}>
      <Navbar />
      
      <div className="flex-1 max-w-4xl mx-auto px-6 lg:px-8 bg-white p-10 rounded-2xl shadow-sm border border-gray-100 my-16">
        
        <div className="mb-10 border-b border-gray-200 pb-8">
          <h1 className="text-4xl font-extrabold text-gray-900 tracking-tight mb-4">Terms and Conditions</h1>
          <p className="text-gray-500 text-lg">Last Updated: March 30, 2026</p>
          <p className="text-gray-600 mt-4 leading-relaxed">
            By accessing or using the <span className="font-semibold text-blue-600">Arogya360 (Smart Health Care)</span> platform—whether as a Citizen, a registered healthcare facility (Hospital), or a Government Authority—you agree to be bound by these Terms and Conditions ("Terms"). If you disagree with any part of these terms, you may not access the service.
          </p>
        </div>

        <div className="space-y-8 text-gray-700">
          
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
              <span className="text-red-500">1.</span> Emergency Services Disclaimer
            </h2>
            <p className="leading-relaxed mb-3">
              The built-in Emergency SOS system relies strictly on network connectivity and GPS accuracy.
              <span className="font-semibold text-red-600"> Never rely solely on Arogya360 for life-threatening emergencies if you are in network dead zones. Always call standard national emergency helplines directly if our system fails to dispatch a responder.</span>
            </p>
          </section>

          <section className="bg-amber-50 p-6 rounded-xl border border-amber-200">
            <h2 className="text-2xl font-bold text-amber-900 mb-4 flex items-center gap-2">
              <span className="text-amber-600">2.</span> AI and Machine Learning Disclaimer
            </h2>
            <p className="leading-relaxed mb-3 font-medium text-amber-800">
              The Arogya360 platform incorporates artificial intelligence (AI) and machine learning (ML) models engineered to assist in:
            </p>
            <ul className="list-disc pl-6 space-y-3 leading-relaxed text-amber-800">
              <li><strong>Disease Progression Forecasting:</strong> Predicting potential regional outbreaks utilizing Python-based data models.</li>
              <li><strong>Symptom Checkers:</strong> Guiding citizens on potential medical conditions.</li>
            </ul>
            <p className="leading-relaxed mt-4 font-bold text-amber-900">
              IMPORTANT: These AI/ML outputs are for informational and administrative purposes only. They DO NOT constitute professional medical advice, diagnosis, or treatment. Always consult a qualified physician or healthcare provider regarding any medical condition.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
              <span className="text-blue-500">3.</span> Hospital Compliance & Fraud Detection
            </h2>
            <p className="leading-relaxed mb-3">
              Hospitals registering on Arogya360 agree to strict operational transparency.
            </p>
            <ul className="list-disc pl-6 space-y-3 leading-relaxed">
              <li><strong>Accurate Reporting:</strong> Hospitals must maintain real-time, accurate counts of available beds, active patient cases, and disease tracking metrics.</li>
              <li><strong>ML Trust Score Audits:</strong> Our system actively monitors for discrepancies (e.g., claiming 100% capacity while admitting zero new patients). A low "Trust Score" generated by our ML backend indicates fraudulent activity.</li>
              <li><strong>Authority Suspension:</strong> Government Authorities reserve the absolute right to suspend, block, or permanently delete any hospital from the network found in violation of these reporting terms, bypassing administrative warnings.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
              <span className="text-blue-500">4.</span> Citizen Data Accuracy
            </h2>
            <p className="leading-relaxed mb-3">
              Users ("Citizens") creating profiles must provide accurate contact and physiological details (age, blood group) as this data may be transmitted to Emergency responders. Any intentional falsification of health records on your profile may lead to an immediate account ban.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
              <span className="text-blue-500">5.</span> Intellectual Property
            </h2>
            <p className="leading-relaxed">
              The platform design, source code, data visualization dashboards, smart analytics models, and the "Arogya360" brand identity are the exclusive property of the development team (Sanket Sutar, Onkar Jadhavar, Saurabh Taur, Rohan Umbarepatil) and the governing municipality. Unauthorized scraping, replication, or distribution of the ML models or UI is strictly prohibited.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
              <span className="text-blue-500">6.</span> Data Modification and Revisions
            </h2>
            <p className="leading-relaxed">
              We reserve the right to modify these Terms at any time. Major changes affecting privacy or hospital reporting rules will be broadcasted to all hospitals and citizens via our built-in notification dashboard at least 7 days before going into effect.
            </p>
          </section>

          <div className="pt-8 mt-12 border-t border-gray-200 text-center">
            <p className="text-gray-500 font-medium tracking-wide">
              For legal inquiries or to dispute a Trust Score penalty, please contact:
            </p>
            <a href="mailto:legal@arogya360.in" className="text-blue-600 font-bold hover:underline text-lg mt-2 inline-block">
              legal@arogya360.in
            </a>
          </div>

        </div>
      </div>
      
      <Footer />
    </div>
  );
};

export default TermsConditions;
